
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mezo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'mezo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  mezo:
    +dbt-osmosis: "{model}.yml"
    submission_method: bigframes
    notebook_template_id: 6574243905263370240
    packages: []
    timeout: 3000
    # Config indicated by + and applies to all files under models/example/
    10_staging:
      schema: "staging"
      +materialized: view
    50_intermediate:
      schema: "intermediate"
      +materialized: view
    80_marts:
      schema: "marts"
      +materialized: table
  twitter_ads:
    +schema: "intermediate"
    staging:
      +schema: "staging"
seeds:
  mezo:
    +dbt-osmosis: "{model}.yml"

vars:
    twitter_ads_schema: raw_paid_twitter_ads
    twitter_ads_database: mezo-portal-data
    twitter_ads__using_keywords: False
    segment_sessionization_trailing_window: 3
    segment_inactivity_cutoff: 30 * 60
    segment_pass_through_columns: []
    segment_bigquery_partition_granularity: "day"
    session_metrics:
      - event_name: "button_clicked"
        metric_name: "button_clicks"
      - event_name: "page_view"
        metric_name: "page_views"
      - event_name: "signed_up"
        metric_name: "sign_ups"
      - event_name: "wallet_connected"
        metric_name: "wallet_connections"
      - event_name: "asset_swapped"
        metric_name: "asset_swaps"
      - event_name: "signed_in"
        metric_name: "sign_ins"
      - event_name: "swap_assets_started"
        metric_name: "swap_assets_starts"
      - event_name: "sign_up_started"
        metric_name: "sign_up_starts"
      - event_name: "funds_added"
        metric_name: "funds_additions"
      - event_name: "pool_liquidity_added"
        metric_name: "pool_liquidity_additions"
      - event_name: "add_funds_started"
        metric_name: "add_funds_starts"
      - event_name: "vault_assets_started"
        metric_name: "vault_assets_starts"
      - event_name: "username_updated"
        metric_name: "username_updates"
      - event_name: "assets_vaulted"
        metric_name: "assets_vaulted"
      - event_name: "musd_borrow_started"
        metric_name: "musd_borrow_starts"
      - event_name: "pool_liquidity_withdrawn"
        metric_name: "pool_liquidity_withdrawals"
      - event_name: "musd_donated"
        metric_name: "musd_donations"
      - event_name: "market_spend_started"
        metric_name: "market_spend_starts"
      - event_name: "musd_borrowed"
        metric_name: "musd_borrows"
      - event_name: "item_purchased"
        metric_name: "items_purchased"
      - event_name: "repay_loan_started"
        metric_name: "repay_loan_starts"
      - event_name: "loan_repaid"
        metric_name: "loans_repaid"
      - event_name: "loan_increased_reduced_ratio"
        metric_name: "loan_increase_reduce_ratio"
      - event_name: "increase_loan_started"
        metric_name: "increase_loan_starts"
      - event_name: "loan_increased"
        metric_name: "loans_increased"
      - event_name: "loan_collateral_deposited"
        metric_name: "loan_collateral_deposits"
      - event_name: "market_spend_completed"
        metric_name: "market_spend_completions"
      - event_name: "loan_collateral_withdrawn"
        metric_name: "loan_collateral_withdrawals"
      - event_name: "withdraw_loan_collateral_started"
        metric_name: "withdraw_loan_collateral_starts"
      - event_name: "deposit_loan_collateral_started"
        metric_name: "deposit_loan_collateral_starts"
      - event_name: "borrow_more_balance_confirmed"
        metric_name: "borrow_more_balance_confirmations"
      - event_name: "assets_swapped"
        metric_name: "assets_swaps"
      - event_name: "borrow_repay_started"
        metric_name: "borrow_repay_starts"
      - event_name: "borrow_repay"
        metric_name: "borrow_repays"
      - event_name: "market_donation_success"
        metric_name: "market_donation_successes"
      - event_name: "borrow_collateral_deposit_started"
        metric_name: "borrow_collateral_deposit_starts"
      - event_name: "borrow_more_increase_coll"
        metric_name: "borrow_more_increase_coll"
      - event_name: "borrow_more_strategy_increase_coll"
        metric_name: "borrow_more_strategy_increase_coll"
      - event_name: "borrow_collateral_deposit"
        metric_name: "borrow_collateral_deposits"
      - event_name: "borrow_more_button_clicked"
        metric_name: "borrow_more_button_clicks"
      - event_name: "borrow_more_confirm_increase_coll"
        metric_name: "borrow_more_confirm_increase_coll"
      - event_name: "llm_share"
        metric_name: "llm_shares"
      - event_name: "borrow_more_strategy_reduce_ratio"
        metric_name: "borrow_more_strategy_reduce_ratio"
