mezo:
  outputs:
    prod:
      dataset: dbt
      job_execution_timeout_seconds: 300
      compute_region: europe-west4
      gcs_bucket: mezo-prod-dp-dwh-dbt-cs-0
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: mezo-portal-data
      threads: 10
      type: bigquery
  target: prod
