mezo:
  outputs:
    prod:
      dataset: dbt
      job_execution_timeout_seconds: 300
      compute_region: europe-west4
      gcs_bucket: mezo-prod-dp-dwh-dbt-cs-0
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: mezo-portal-data
      threads: 10
      type: bigquery
      impersonate_service_account: "{{ env_var('DBT_SERVICE_ACCOUNT') }}"
    pr:
      type: bigquery
      method: oauth
      compute_region: europe-west4
      gcs_bucket: mezo-prod-dp-dwh-dbt-cs-0
      retries: 1
      project: mezo-portal-data
      dataset: "pr_{{ var('schema_id') }}"
      threads: 4
      job_execution_timeout_seconds: 1200
      priority: interactive
      location: EU
      impersonate_service_account: "{{ env_var('DBT_SERVICE_ACCOUNT') }}"
  target: prod
