[project]
name = "dbt-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-bigquery>=1.10.0",
    "dbt-core>=1.10.4",
    "rpds-py>=0.26.0",
]

[dependency-groups]
dev = [
    "sqlfluff>=3.4.2",
]
