{{
    dbt_utils.union_relations(
        relations=[
            ref("int_paid__manual_cost_import"),
            ref("int_paid__twitter"),
        ],
        include=[
            "date_day",
            "clicks",
            "impressions",
            "spend",
            "campaign_id",
            "referrer_source",
            "referrer_medium",
        ],
        source_column_name="source_relation",
    )
}}
