version: 2

models:
  - name: int_segment_web_user_stitching
    description: "{{doc('segment_web_user_stitching')}}"
    columns:
      - name: anonymous_id
        data_tests:
          - unique
          - not_null

  - name: int_segment_web_page_views__sessionized
    description: "{{doc('segment_web_page_views__sessionized')}}"
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: int_segment_web_sessions__initial
    description: "{{doc('segment_web_sessions__initial')}}"
    columns:
      - name: session_id
        data_tests:
          - unique
          - not_null

  - name: int_segment_web_sessions__stitched
    description: "{{doc('segment_web_sessions__stitched')}}"
    columns:
      - name: session_id
        description: ''
        data_tests:
          - unique
          - not_null

  - name: int_segment_web_sessions
    description: "{{doc('segment_web_sessions')}}"
    columns:
      - name: session_id
        description: ''
        data_tests:
          - unique
          - not_null
