name: Build and Deploy to Cloud Run Job

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: mezo-portal-data
      REGION: europe-west3
      SERVICE_NAME: dbt-mezo
      IMAGE: europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/dbt-repo/dbt-mezo:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
          token_format: 'access_token'
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy $SERVICE_NAME \
            --image $IMAGE \
            --tasks 1 \
            --set-env-vars SLEEP_MS=10000,FAIL_RATE=0.1 \
            --max-retries 5 \
            --region $REGION \
            --project $PROJECT_ID
