name: CI Run on Pull Request
env:
  FAST_WIF_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  CICD_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  DBT_SERVICE_ACCOUNT: ${{ secrets.PROD_DP_ORC_CMP_SA }}
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"
  pull-requests: "write"

jobs:
  ci_job:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --dev

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.FAST_WIF_PROVIDER }}
          service_account: ${{ env.CICD_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      - name: Run dbt debug
        run: |
          uv run dbt debug --target ${{ env.TARGET }}

      - name: Run dbt deps
        run: |
          uv run dbt deps --target ${{ env.TARGET }}

      - name: Get Schema ID
        id: schema_id
        run: echo "SCHEMA_ID=${{ github.event.pull_request.number }}__${{ github.sha }}" >> $GITHUB_ENV

      - name: pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Run dbt build
        id: first_try
        run: |
            uv run dbt build --target ${{ env.TARGET }} --vars "schema_id: $SCHEMA_ID"

      - name: Run dbt build another time to check incremental models
        id: incremental_try
        run: |
          uv run dbt build --select config.materialized:incremental --target ${{ env.TARGET }} --vars "schema_id: $SCHEMA_ID"
